admin_bienvenida:
    path: /home/
    defaults: { _controller: AdminBundle:Default:bienvenida }
admin_menu:
    path: /menu/
    defaults: { _controller: AdminBundle:Default:menu }
admin_menu_boostrap:
    path: /menuB/
    defaults: { _controller: AdminBundle:Default:menuB }