presupuesto:
    resource: "@PresupuestoBundle/Resources/config/routing.yml"
    prefix:   /

recepcion:
    resource: "@RecepcionBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

