security:
    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: sitio_login
                check_path: sitio_login_check
            
    access_control:
        - { path: ^/inicio_sesion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_ADMIN }
    
    providers:
        Admin:
            entity: { class: Garbodor\RecepcionBundle\Entity\Usuario, property: rut }
    
    encoders:
        Garbodor\RecepcionBundle\Entity\Usuario: { algorithm: sha512, iterations:10 }