parameters:
#    presupuesto.example.class: Garbodor\PresupuestoBundle\Example

services:
#    presupuesto.example:
#        class: %presupuesto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
