parameters:
#    recepcion.example.class: Garbodor\RecepcionBundle\Example

services:
#    recepcion.example:
#        class: %recepcion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
